### ISSUE TITLE
ENH: make virtual tag operator list the same length as tags or length 1

### ISSUE THREAD

**Issue by jbolorinos** [we3lab/pype-schema#60]
## Use Case
I am running into a use case where I programmatically need to subtract one or more tags in a virtual tag operation (e.g., need to subtract battery tags from "VirtualDemand_Electricity_InFlow if it is included in a meter's tag). Since the operations are of length one less than the number of tags, it is very difficult to programmatically determine which operator to drop. You could have a situation where you want to subtract two tags from one tag, the operations could be one of `["-","+","-"]`, `["+","-","-"]` or `["-","-","+"]` and that involves some very tedious logic.

## Solution
Why not just define a virtual tag as an addition of tags with either a "+" or a "-"? You could define a virtual tag as a negative of a tag (so one operation, one tag) or as a positive of a tag (so a virtual tag of itself). To me this makes intuitive sense and makes virtual tags a lot easier to work with programmatically. So e.g. `[+,-,+]` would just be `+Tag1-Tag2+Tag3` and `[-,-,+]` would be 
`[-Tag1,-Tag2,+Tag3]`

**Comment by fletchapin** [comment]
Closed by #74
