### ISSUE TITLE
ENH: embed lambda function strings into virtual tags

### ISSUE THREAD

**Issue by jbolorinos** [we3lab/pype-schema#65]
## Use Case
Sometimes virtual tags are more complicated functions of constituent tag objects and we want to code that structure into the network, for example, to change the units (to get the volume (in STP equivalents) of biogas from a pressure reading)

## Solution

in the aggregation function, specify a lambda function string with as many arguments as constituent tags:

`"binary_operations": "lambda p, T: convert_pressure_to_volume(p,T,485.8,1.15)"`

Where `convert_pressure_to_volume` is a prep_data function (just wrote it :)) and p is the pressure tag, T is the temperature from a tag in the digester in degrees C, 485.8 is the fixed size of the gas storage sphere and 1.15 is the m3/kg of biogas (taken from the internet or we could measure in a lab)

Another example is with unary operations where the lambda function can only specify one argument:

`"unary_operations": "lambda p: convert_pressure_to_volume(p,25,485.8,1.15)"`

## Alternatives
Happy to discuss alternatives tomorrow!

**Comment by fletchapin** [comment]
Closed by #74
