### ISSUE TITLE
ENH: informative debug messages when initializing network from a json file

### ISSUE THREAD

**Issue by jbolorinos** [we3lab/pype-schema#69]
## Use Case
*Please provide a use case to help us understand your request in context*

When initializing a network from a json file, it can be hard to know where the problem is (i.e. which node/connection is mis-specified). Printing the id of the node/connection that is being created can help the user to quickly pinpoint problems in an input json network file

## Solution
Adding a debug argument that prints these informative messages

## Alternatives
An alternative is to just always print an informative message when creating nodes/connections, not great...

**Comment by jbolorinos** [comment]
Working on this on a separate (cloned) branch now, will rebase to main when you merge the pr

**Comment by fletchapin** [comment]
Closed by #74
