### ISSUE TITLE
ENH: Give networks a units attribute

### ISSUE THREAD

**Issue by jbolorinos** [we3lab/pype-schema#70]
## Use Case
*Please provide a use case to help us understand your request in context*
It is sometimes useful to be able to bin networks into units like other objects (e.g. there are 5 sub-circuits in a given electricity network, or something like that)

## Solution
*Please describe your ideal solution*
Give a units attribute to the `network` object

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*
Initialize as many `network` objects as there are units you want to add, this is tedious...

**Comment by jbolorinos** [comment]
@fletchapin  I will add this to my next branch and submit PR alongside verbosity stuff

**Comment by fletchapin** [comment]
Completed in #74
