### ISSUE TITLE
ENH: allow user to select for real or virtual tags

### ISSUE THREAD

**Issue by jbolorinos** [we3lab/pype-schema#71]
## Use Case
*Please provide a use case to help us understand your request in context*
Allow user to select virtual tags or real tags, useful for cases where there is both a real and a virtual tag for a measured quantity

## Solution
*Please describe your ideal solution*

Have a `virtual=True` kwarg in select_objs

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*

Add another attribute? Like `tag_virtuality`?? `tag_type` is already taken

**Comment by fletchapin** [comment]
This should already be possible by passing `obj_type=VirtualTag` or `obj_type=Tag` into `select_objs` so I don't think that a separate flag would be useful. If that solution doesn't work or you think that it would be more elegant to have a separate flag then please let me know of course!
