### ISSUE TITLE
Rename and add content types

### ISSUE THREAD

**Issue by dalyw** [we3lab/pype-schema#77]
## Use Case
- Add "Chemical" for dosing of chemical (e.g. dosing methanol for nutrient removal)
- Rename "untreated sewage" to using “wastewater” so it can be generalized for industrial wastewater
- Rename “treated sewage” to "tertiary effluent" or "disinfected effluent" or something more general 

## Solution
Additional content types

## Alternatives
Add "Other

**Comment by fletchapin** [comment]
`TertiaryEffluent` is already a `ContentsType`. For backwards compatibility I don't remove `ContentsType` but I have introduced the following new `ContentsType` (in `feature/batt-attr`):

- `Disinfectant`
- `Coagulant`
- `Chemical`
- `IndustrialWastewater`
- `MunicipalWastewater`
- `DisinfectedEffluent`
