### ISSUE TITLE
Add unit options

### ISSUE THREAD

**Issue by dalyw** [we3lab/pype-schema#78]
## Use Case
Add unit options for VFD
- Speed (Hz)
- Speed (%)
SCADA systems may use either unit type - and speed may not easily translate to RPM without the equipment documentation

## Solution
Add new unit types

## Alternatives
Using "efficiency" as a % unit

**Comment by fletchapin** [comment]
Added `Speed` to the `TagType` enum in #feature/batt-attr and users can define whatever `Pint` unit they want for each tag (e.g., Hz or %) so this should be all set
