### ISSUE TITLE
ENH: Add RTE and leakage battery node attributes

### ISSUE THREAD

**Issue by jbolorinos** [we3lab/pype-schema#83]
## Use Case

Right now, users wanting to model RTE/leakage have to do this separately but they are attributes of all batteries so it makes sense to put them in the network model.

## Solution

Add `RTE`,`leakage` attributes to battery nodes

## Alternatives

Can't think of any (don't add `RTE`,`leakage` attribute to battery nodes? lol)

**Comment by fletchapin** [comment]
@jbolorinos I just added discharge rate and RTE. For leakage, would it make sense for it to be a quantity with units like `kWh / second`?
